version: "3.8"

services:
  app:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - db
    command: >
      sh -c "npx sequelize-cli db:migrate --config db/config/config.js && npx sequelize-cli db:seed:all --config db/config/config.js && node app.js"

  db:
    image: postgres:15-alpine
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
