version: "3.8"

services:
  app:
    build: .
    entrypoint: ["/app/entrypoint.sh"]
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - db
    command: npm start

  db:
    image: postgres:15-alpine
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRESS_HOST: ${DB_HOST}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
